server:
  port: 9994
spring:
  jpa:
    hibernate:
      ddl-auto: update

    debug: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice
    username: root
    password: sumit
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Booking-Service
eureka:
  client:
    fetch-registry: true
instance:
    prefer-ip-address: true
    register-with-eureka: true
    service-url:
      defaultzone:  http://localhost:8761/eureka

    feign:
    client:
    config:
    default:
     loggerLevel: FULL
    connectTimeout: 2000
    readTimeout: 3000
    resilience4j:
    circuitbreaker:
    instances:
    userService:
    registerHealthIndicator: true
    slidingWindowSize: 5
    failureRateThreshold: 50
    waitDurationInOpenState: 10s